# Generated by Django 3.1.7 on 2021-12-26 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('bookname', models.TextField(max_length=100)),
                ('bookid', models.TextField(default=uuid.UUID('11ec1f78-6630-11ec-8da2-fde70f131a0e'), max_length=16, primary_key=True, serialize=False, unique=True)),
                ('author', models.TextField(max_length=150)),
                ('summary', models.TextField(max_length=500)),
                ('bookpic', models.URLField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
