# Generated by Django 3.1.7 on 2021-12-26 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_bookdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='bookid',
            field=models.TextField(default=uuid.UUID('9c9562b4-6637-11ec-bfbd-fde70f131a0e'), max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default='john@doe.com', max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
