# Generated by Django 3.1.7 on 2021-12-26 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20211226_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='bookid',
            field=models.TextField(default=uuid.UUID('9486f009-665a-11ec-be42-fde70f131a0e'), max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
