# Generated by Django 3.1.7 on 2021-12-27 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211226_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='genre',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='bookid',
            field=models.TextField(default=uuid.UUID('19de14ff-671a-11ec-a5d5-fde70f131a0e'), max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
