# Generated by Django 3.1.7 on 2021-12-28 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20211227_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='bookid',
            field=models.TextField(default=uuid.UUID('d4032d10-67ad-11ec-a509-cb5e2e676fe0'), max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
