# Generated by Django 3.1.7 on 2021-12-28 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20211228_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='bookid',
            field=models.TextField(default=uuid.UUID('4806fad9-67c7-11ec-82f4-cb5e2e676fe0'), max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.TextField(max_length=15, unique=True),
        ),
    ]
