# Generated by Django 3.1.7 on 2021-12-28 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20211228_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='bookid',
            field=models.TextField(default=uuid.UUID('7550a99c-67c7-11ec-a3ab-cb5e2e676fe0'), max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.TextField(default='foobar', max_length=15, unique=True),
        ),
    ]
