# Generated by Django 3.1.7 on 2021-12-28 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20211228_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='bookpic',
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='book',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='bookpic_img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='bookpic_url',
            field=models.URLField(default='jon@doe.com'),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='bookid',
            field=models.TextField(default=uuid.UUID('d82a32ae-67e4-11ec-856a-b19dc649745c'), max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
